# Generated by Django 4.1.1 on 2022-11-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('GID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterModel',
            fields=[
                ('PARAMID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PARAMNAME', models.CharField(max_length=225)),
                ('DISCRIPTION', models.TextField(blank=True, null=True)),
                ('DEFAULT_VALUE', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('PID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(null=True, upload_to='Images')),
                ('GID', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='Home.genremodel')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('MODELID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('MODELNAME', models.CharField(blank=True, max_length=225, null=True)),
                ('TYPE', models.CharField(blank=True, choices=[('Classification', 'Classification'), ('Regression', 'Regression')], max_length=225, null=True)),
                ('PARAMS', models.ManyToManyField(to='Home.parametermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('INTRODUCTION', models.TextField(null=True)),
                ('MODELS', models.TextField(null=True)),
                ('FEATURES', models.TextField(null=True)),
                ('APPLICATION', models.TextField(null=True)),
                ('PID', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='Home.projectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEATURESMODEL', models.JSONField(null=True)),
                ('NAME', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.informationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BuildMLModel',
            fields=[
                ('BID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=50, null=True)),
                ('DATASET', models.FileField(null=True, upload_to='staticfiles/Dataset')),
                ('TRAIN_X', models.FileField(null=True, upload_to='staticfiles/Dataset/Traning')),
                ('TEST_X', models.FileField(null=True, upload_to='staticfiles/Dataset/Testing')),
                ('TRAIN_Y', models.FileField(null=True, upload_to='staticfiles/Dataset/Training')),
                ('TEST_Y', models.FileField(null=True, upload_to='staticfiles/Dataset/Testing')),
                ('T_ENCODER', models.FileField(null=True, upload_to='staticfiles/Dataset/Encoder')),
                ('TYPE', models.CharField(max_length=50, null=True)),
                ('MODELID', models.CharField(max_length=10, null=True)),
                ('MODEL', models.FileField(null=True, upload_to='staticfiles/Models')),
                ('UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.user')),
            ],
        ),
    ]
