# Generated by Django 4.1.1 on 2022-11-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildMLModel',
        ),
    ]
