# Generated by Django 4.1.1 on 2022-11-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Home', '0002_delete_buildmlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildMLModel',
            fields=[
                ('BID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=50, null=True)),
                ('DATASET', models.FileField(null=True, upload_to='staticfiles/Dataset')),
                ('TRAIN_X', models.FileField(null=True, upload_to='staticfiles/Dataset/Traning')),
                ('TEST_X', models.FileField(null=True, upload_to='staticfiles/Dataset/Testing')),
                ('TRAIN_Y', models.FileField(null=True, upload_to='staticfiles/Dataset/Training')),
                ('TEST_Y', models.FileField(null=True, upload_to='staticfiles/Dataset/Testing')),
                ('T_ENCODER', models.FileField(null=True, upload_to='staticfiles/Dataset/Encoder')),
                ('TYPE', models.CharField(max_length=50, null=True)),
                ('MODELID', models.CharField(max_length=10, null=True)),
                ('MODEL', models.FileField(null=True, upload_to='staticfiles/Models')),
                ('UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.user')),
            ],
        ),
    ]
