# Generated by Django 4.1.1 on 2022-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_informationmodel_image_alter_buildmlmodel_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='NAME',
            field=models.CharField(max_length=20),
        ),
    ]
