# Generated by Django 4.1.1 on 2022-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_informationmodel_image_alter_buildmlmodel_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmlmodel',
            name='F_ENCODER',
            field=models.FileField(null=True, upload_to='Dataset/Encoder'),
        ),
    ]
