# Generated by Django 4.1.1 on 2022-11-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_demomodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='NAME',
            field=models.CharField(max_length=100),
        ),
    ]
