# Generated by Django 4.1.1 on 2022-11-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_buildmlmodel_f_encoder'),
        ('Home', '0006_alter_demomodel_name'),
    ]

    operations = [
    ]
