# Generated by Django 4.1.1 on 2022-11-07 17:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=20, unique=True)),
                ('MOBILE', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
    ]
